# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d59e0e35adc81e4523edabc37d3a0a833a1abacecef709ae36f8c1d01c74c58b70980ad9c6c4b5f35ca71b6f7004dede38e3722e0f36f9269ecd63e22f943842

test:
  secret_key_base: 4d876983f36c40bea1a8772cfabe3fb997be5653d8252bcd4f0edaffffc3c655d4250ecd0709207674882cc6579e4149bd113a24d9ae7d85f2ab796325a2cd71

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
